title: GeFL
description: Project page for GeFL
theme: just-the-docs

url: https://honggkang.github.io/gefl/

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

favicon_ico: "/resources/favicon.ico"

